# Generated by Django 5.0.6 on 2024-05-22 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='recipe_description',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='image',
            new_name='recipe_image',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name',
            new_name='recipe_name',
        ),
    ]
