# Generated by Django 5.0.6 on 2024-07-02 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name'], 'verbose_name': 'student'},
        ),
    ]
