# Generated by Django 5.0.6 on 2024-07-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_alter_subjectmarks_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentid',
            name='student_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
