# Generated by Django 5.0.6 on 2024-07-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0012_alter_reportcard_date_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
